### PR TITLE
[FetchIt!] STL updates for new largeGear

### LINKED ISSUE #50: Update 3D Parts
The 3D parts were originally sized before we were able to turn on the Schunk Machine.

It turned out, that the chuck was not able to close as much as we expected. We've made the shaft of the large gear larger to fit into the machine.

https://github.com/fetchrobotics/fetchit/pull/2

@velveteenrobot

### PR DESCRIPTION
**Pull request by moriarty**
This fixes #50 in part, the stl files are done but not the dae files.

These changes correspond to fetchrobotics/fetchit#2

@RDaneelOlivav I'm not actually familiar with Blender or dae files and tried to export them but they didn't look correct. Can you update the dae files and submit a PR to this branch?

### CODE REVIEW

**Comment by RDaneelOlivav** [comment]
@moriarty Ok, I'll check the new STL, compare them to see the differences and adapt the Daes if needed. Because the STLs are used for the collisions mainly to minimize the load in the physics contact simulation. Depending on how I'll change the daes ( visual meshes ) to match those changes.

**Review by cjds — DISMISSED** [review]

**Comment by moriarty** [comment]
👍

**Comment by RDaneelOlivav** [comment]
Ok I commited the changes to the update-parts branch on moriarty/fetch_gazebo.
commit a8669754379c237ade94d8f5a1282cc9deee8924.

I added the new versions of the dae files, with the same colors as the previous ones and rescaled them to be exactly the same scale also as the originals.

Sorry if I commited where I shouldn't have, I'm unfamiliar with projects with so many micro commits, forked versions, and branches. 

Please indicate me for the next time what would have been the preferable procedure for the next time ;).

Do I have to make a pull request then of these changes now?
@moriarty

**Comment by moriarty** [comment]
Looks fine. Committing on top of this branch is perfect.

Usually, I merge with squash and merge, so there aren't that many commits.

I'll merge this now, and trust that you tested it, and then run bloom-release to Indigo & Melodic.

With PR #38 I didn't squash and merge :cry:

**Review by narora1 — APPROVED** [review]

**Pull request merged**
