### PR TITLE
Add srdf for fetch gazebo to disable default collisions

### PR DESCRIPTION
**Pull request by 708yamaguchi**
I add srdf for fetch gazebo to disable default collisions (collisions between `base_link` and `bl/br/fl/fr_caster_link`).

This file is mostly a copy of fetch.srdf.
https://github.com/fetchrobotics/fetch_ros/blob/melodic-devel/fetch_moveit_config/config/fetch.srdf

The difference is the addition of some disabled_collision tags.
```
    <!-- Gazebo only -->
    <disable_collisions link1="base_link" link2="bl_caster_link" reason="Default" />
    <disable_collisions link1="base_link" link2="br_caster_link" reason="Default" />
    <disable_collisions link1="base_link" link2="fl_caster_link" reason="Default" />
    <disable_collisions link1="base_link" link2="fr_caster_link" reason="Default" />
```

|real robot urdf|gazebo urdf|base_link.dae|
|---|---|---|
||||

Based on https://github.com/fetchrobotics/fetch_ros/pull/152

### CODE REVIEW

**Comment by knorth55** [comment]
It seems most of the code is a copy of `fetch.srdf`.

How about using xacro as baxter and include `fetch.srdf` in fetch_gazebo.srdf`?
https://github.com/ros-planning/moveit_robots/blob/kinetic-devel/baxter/baxter_moveit_config/launch/planning_context.launch#L23-L28

**Comment by 708yamaguchi** [comment]
@knorth55
Thank you, I updated to use xacro.

**Review by zzhu-fetch — DISMISSED** [review]
:+1:

**Review by erelson — APPROVED** [review]

**Comment by erelson** [comment]
Hi @708yamaguchi, Sorry this PR languished so long. I was hoping to get to Gazebo a bit after finishing the Noetic release, but that dragged out and I forgot.

I added a comment to the .srdf.xacro once I understood what was going on.  Makes sense to me!

**Pull request merged**
