### PR TITLE
[FetchIt!] Tapered large gear

### PR DESCRIPTION
**Pull request by velveteenrobot**
Tapered the large gear for easier insertion into the Schunk machine. Tested with teleoping the robot to have it insert the gear and it worked well, easier than before.

@RDaneelOlivav I autogenerated the dae file, so someone might want to verify that it's good. I viewed it in a CAD program and it looked fine, but a second opinion would be great.

### CODE REVIEW

**Comment by moriarty** [comment]
Screenshot from 2019-03-28 10-02-32
Screenshot from 2019-03-28 10-03-23

That's really large. The Fetch can only lift 6 Kg

**Comment by moriarty** [comment]
@RDaneelOlivav how did you scale down the STL file? To which scale did you change and recreate the models?

@ajzeller: Either the scale isn't being accounted for or we must be exporting our STL files from SolidWorks at an incorrect scale.

@jacobperron: didn't you mention something similar recently?

**Review by moriarty — CHANGES_REQUESTED** [review]
Scale is incorrect :disappointed:

**Comment by jacobperron** [comment]
> @jacobperron: didn't you mention something similar recently?

Unrelated issue in RViz.

**Comment by RDaneelOlivav** [comment]
@velveteenrobot @moriarty 
Yeah, this scale problem is always detected in blender because in CAD programs for some reason it's not respected or at least doesn't transfer correctly to Gazebo.
I'll look into this tomorrow, is that ok?
It's just rescaling it and that's it.

**Comment by RDaneelOlivav** [comment]
Screenshot from 2019-03-29 17-06-18

[ROSJECT to test it](http://www.rosject.io/l/8ccc520/)

Uploaded the scale correction.
@velveteenrobot 
Here I've made a very simple video to give you a way to check that your model has the right dimensions and rescale it and reposition the origin if not ;): [RESCALE in BLENDER](https://youtu.be/O2_rFMQEUTw)

**Pull request merged**
