### PR TITLE
Schunk Machine interface.

### PR DESCRIPTION
**Pull request by velveteenrobot**
ROS Node to control the Schunk Machine through an actionlib interface.
Tested with a real Fetch.

Naming/formatting/everything suggestions welcome.

### CODE REVIEW

**Review by cjds — APPROVED** [review]

**Comment by moriarty** [comment]
Ah now I see the problem you mentioned earlier more clearly :confused: 

This node lives and runs on the RPi itself correct? But by placing it into `fetchit_challenge` it now shares a run-time dependency with `fetch_gazebo` and `gazebo_ros` 

If we place it into another location, then we can cut down the dependencies.

But then the question comes back to where do we place it?

[Build Status](http://build.ros.org/job/Mbin_ubhf_uBhf__fetchit_challenge__ubuntu_bionic_armhf__binary/) It's good to see that the build is passing at the moment but if you wanted to `sudo apt install ros-melodic-fetchit-challenge` on an RPi it would then install gazebo onto the RPi?

- fetchrobotics/fetch_gazebo in another sub-directory?
    - keeps things all close together for now which is a pro
    - has nothing to do with gazebo which is a con
- fetchrobotics/fetchit
    - currently underutilized, but it doesn't contain any ROS code, and we want the STL files to be easy to find so that people can print them, also I wanted to move the rulebook out of a private google document into this at some point.
- fetchrobotics/fetchit_challenge or fetchrobotics/fetchit_ros **new** repositories?
    - pro: could move fetchit_challenge from here into there and rename it fetchit_sim and keep both fetchit_sim and non-sim all together. 
- fetchrobotics/fetch_ros - I don't think it should go here, this our core ros packages
- fetchrobotics/fetch_demos - newly created for publishing the demonstrations for interns, not really the correct place

For this year it's probably fine to just keep this here so that everything is all together and then it will just be added to the list of things to do to refactor and move things around.

**Comment by RDaneelOlivav** [comment]
@velveteenrobot , could we have the definition of all these actions what they will do? Is because we should adapt this to the simulated shunk machine so that it behaves exactly in the same way as the real one does. I created the shunk machine with very simple topic that made it spin but I suppose that there is a lot to it.

**Comment by moriarty** [comment]
@velveteenrobot & @RDaneelOlivav I think for now it will be easiest to keep everything in this fetch_gazebo repository and we can move things around after ICRA

**Review by moriarty — APPROVED** [review]
I think we should move these around after ICRA but for now it's much easier to keep it all together.

**Comment by RDaneelOlivav** [comment]
Great @velveteenrobot , I'll start as soon as possible with these new tasks, I might not starts until Wednesday because of other tasks I have, but its high priority for sure ;).

Also, @moriarty told me that the actions open and close the Chuck. Anything else? So the fetch robot exactly what will have to do in reference to the shunk machine? Through ROS they will be able to open and close the Chuck and anything else? Like starting the program of mechanization? Open and close the door is done through ROS or is it opened through manipulation of the fetch robot?

**Pull request merged**
