### PR TITLE
add costmap_2d to run_depends

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by mikeferguson** [comment]
fetch_gazebo_demo depends on fetch_navigation, which depends on navigation, which depends on costmap_2d -- are you not getting costmap_2d installed?

**Comment by k-okada** [comment]
no i did not

## 

◉ Kei Okada

On Wed, Jun 24, 2015 at 12:27 PM, Michael Ferguson <notifications@github.com

**Comment by k-okada** [comment]
sorry, removing costmap-2d and reinstall fetch-gazebo-demo again installed
costmap_2d, it was something wrong to me this morning.

```
$ sudo apt-get remove ros-indigo-costmap-2d
[sudo] password for k-okada:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer
required:
  libbtf1.2.0 libcsparse3.1.2 libcxsparse3.1.2 libklu1.2.1 libldl2.1.0
  libspqr1.3.1 libsuitesparse-dev linux-headers-3.13.0-32
  linux-headers-3.13.0-32-generic linux-image-3.13.0-32-generic
  linux-image-3.13.0-39-generic linux-image-extra-3.13.0-32-generic
  linux-image-extra-3.13.0-39-generic ros-indigo-actionlib-tutorials
  ros-indigo-common-tutorials ros-indigo-concert-conductor
  ros-indigo-concert-master ros-indigo-concert-msgs
  ros-indigo-concert-scheduler-requests ros-indigo-concert-schedulers
  ros-indigo-concert-service-admin ros-indigo-concert-service-manager
  ros-indigo-fake-localization ros-indigo-fetch-description
  ros-indigo-fetch-gazebo ros-indigo-fetch-moveit-config
  ros-indigo-grasping-msgs ros-indigo-moveit-python
  ros-indigo-nodelet-tutorial-math ros-indigo-open-karto
  ros-indigo-pluginlib-tutorials ros-indigo-robot-controllers
  ros-indigo-robot-controllers-interface ros-indigo-robot-controllers-msgs
  ros-indigo-rocon-launch ros-indigo-rosapi ros-indigo-rosauth
  ros-indigo-rosbridge-library ros-indigo-rosbridge-server
  ros-indigo-rospy-message-converter ros-indigo-scheduler-msgs
  ros-indigo-simple-grasping ros-indigo-slam-karto
  ros-indigo-sparse-bundle-adjustment ros-indigo-stage-ros
ros-indigo-stdr-gui
  ros-indigo-stdr-msgs ros-indigo-stdr-parser ros-indigo-stdr-resources
  ros-indigo-stdr-robot ros-indigo-stdr-server ros-indigo-turtle-actionlib
  ros-indigo-voxel-grid ros-indigo-yocs-math-toolkit ros-indigo-yocs-msgs
  ros-indigo-yocs-virtual-sensor
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  ros-indigo-base-local-planner ros-indigo-carrot-planner
  ros-indigo-clear-costmap-recovery ros-indigo-concert-service-gazebo
  ros-indigo-costmap-2d ros-indigo-dwa-local-planner
  ros-indigo-fetch-depth-layer ros-indigo-fetch-gazebo-demo
  ros-indigo-fetch-navigation ros-indigo-gazebo-concert
  ros-indigo-global-planner ros-indigo-move-base
  ros-indigo-move-slow-and-clear ros-indigo-nav-core ros-indigo-navfn
  ros-indigo-navigation ros-indigo-rotate-recovery
ros-indigo-turtlebot-gazebo
  ros-indigo-turtlebot-navigation ros-indigo-turtlebot-simulator
  ros-indigo-turtlebot-stage ros-indigo-turtlebot-stdr
0 upgraded, 0 newly installed, 22 to remove and 17 not upgraded.
After this operation, 14.9 MB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 512994 files and directories currently installed.)
Removing ros-indigo-turtlebot-simulator (2.2.0-0trusty-20150609-1121-+0000)
...
Removing ros-indigo-turtlebot-stdr (2.2.0-0trusty-20150609-0625-+0000) ...
Removing ros-indigo-turtlebot-stage (2.2.0-0trusty-20150609-0624-+0000) ...
Removing ros-indigo-gazebo-concert (0.6.7-0trusty-20150609-1223-+0000) ...
Removing ros-indigo-concert-service-gazebo
(0.1.11-0trusty-20150609-1200-+0000) ...
Removing ros-indigo-turtlebot-gazebo (2.2.0-0trusty-20150609-1108-+0000) ...
Removing ros-indigo-turtlebot-navigation
(2.3.3-0trusty-20150609-0601-+0000) ...
Removing ros-indigo-fetch-depth-layer (0.5.13-0trusty-20150613-2303-+0000)
...
Removing ros-indigo-fetch-gazebo-demo (0.5.0-0trusty-20150613-2320-+0000)
...
Removing ros-indigo-fetch-navigation (0.5.13-0trusty-20150613-2317-+0000)
...
Removing ros-indigo-navigation (1.12.4-0trusty-20150609-0137-+0000) ...
Removing ros-indigo-move-base (1.12.4-0trusty-20150609-0132-+0000) ...
Removing ros-indigo-carrot-planner (1.12.4-0trusty-20150609-0122-+0000) ...
Removing ros-indigo-clear-costmap-recovery
(1.12.4-0trusty-20150609-0116-+0000) ...
Removing ros-indigo-rotate-recovery (1.12.4-0trusty-20150609-0127-+0000) ...
Removing ros-indigo-global-planner (1.12.4-0trusty-20150609-0127-+0000) ...
Removing ros-indigo-navfn (1.12.4-0trusty-20150609-0115-+0000) ...
Removing ros-indigo-dwa-local-planner (1.12.4-0trusty-20150609-0122-+0000)
...
Removing ros-indigo-move-slow-and-clear
(1.12.4-0trusty-20150609-0118-+0000) ...
Removing ros-indigo-base-local-planner (1.12.4-0trusty-20150609-0114-+0000)
...
Removing ros-indigo-nav-core (1.12.4-0trusty-20150609-0108-+0000) ...
Removing ros-indigo-costmap-2d (1.12.4-0trusty-20150608-1755-+0000) ...
k-okada@kokada-t440s:/tmp/fetch_gazebo/fetch_gazebo_demo$ sudo apt-get
install ros-indigo-fetch-gazebo-demo
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer
required:
  linux-headers-3.13.0-32 linux-headers-3.13.0-32-generic
  linux-image-3.13.0-32-generic linux-image-3.13.0-39-generic
  linux-image-extra-3.13.0-32-generic linux-image-extra-3.13.0-39-generic
  ros-indigo-actionlib-tutorials ros-indigo-common-tutorials
  ros-indigo-concert-conductor ros-indigo-concert-master
  ros-indigo-concert-msgs ros-indigo-concert-scheduler-requests
  ros-indigo-concert-schedulers ros-indigo-concert-service-admin
  ros-indigo-concert-service-manager ros-indigo-nodelet-tutorial-math
  ros-indigo-pluginlib-tutorials ros-indigo-rocon-launch ros-indigo-rosapi
  ros-indigo-rosauth ros-indigo-rosbridge-library
ros-indigo-rosbridge-server
  ros-indigo-rospy-message-converter ros-indigo-scheduler-msgs
  ros-indigo-stage-ros ros-indigo-stdr-gui ros-indigo-stdr-msgs
  ros-indigo-stdr-parser ros-indigo-stdr-resources ros-indigo-stdr-robot
  ros-indigo-stdr-server ros-indigo-turtle-actionlib
  ros-indigo-yocs-math-toolkit ros-indigo-yocs-msgs
  ros-indigo-yocs-virtual-sensor
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  ros-indigo-base-local-planner ros-indigo-carrot-planner
  ros-indigo-clear-costmap-recovery ros-indigo-costmap-2d
  ros-indigo-dwa-local-planner ros-indigo-fetch-navigation
  ros-indigo-global-planner ros-indigo-move-base
  ros-indigo-move-slow-and-clear ros-indigo-nav-core ros-indigo-navfn
  ros-indigo-navigation ros-indigo-rotate-recovery
The following NEW packages will be installed:
  ros-indigo-base-local-planner ros-indigo-carrot-planner
  ros-indigo-clear-costmap-recovery ros-indigo-costmap-2d
  ros-indigo-dwa-local-planner ros-indigo-fetch-gazebo-demo
  ros-indigo-fetch-navigation ros-indigo-global-planner ros-indigo-move-base
  ros-indigo-move-slow-and-clear ros-indigo-nav-core ros-indigo-navfn
  ros-indigo-navigation ros-indigo-rotate-recovery
0 upgraded, 14 newly installed, 0 to remove and 17 not upgraded.
Need to get 0 B/1,414 kB of archives.
After this operation, 9,731 kB of additional disk space will be used.
Do you want to continue? [Y/n]
``

--
◉ Kei Okada


On Wed, Jun 24, 2015 at 12:31 PM, Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>
wrote:

> no i did not
>
> --
> ◉ Kei Okada
>
>
> On Wed, Jun 24, 2015 at 12:27 PM, Michael Ferguson <
> notifications@github.com> wrote:
>
>> fetch_gazebo_demo depends on fetch_navigation, which depends on
>> navigation, which depends on costmap_2d -- are you not getting costmap_2d
>> installed?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fetchrobotics/fetch_gazebo/pull/4#issuecomment-114717081>
>> .
>>
>
>
```

**Comment by mikeferguson** [comment]
Ok. Just a heads up -- if you are using the public repo (rather than shadow-fixed)  you'll need to also install ros-indigo-fetch-depth-layer (a dependency of fetch-navigation), as that fix did not make it in time to be in the public repo.

**Pull request closed without merging**
